project_id = "flbofahkdtzfhsgehntt"

[functions.ingest-metrics]
verify_jwt = false

[functions.agent-installer]
verify_jwt = false

[functions.cleanup-old-data]
verify_jwt = false

[functions.evaluate-alerts]
verify_jwt = false
